### ISSUE TITLE
Getting error when using yarn to install dependencies

### ISSUE THREAD

**Issue by anthonybrown** [dceddia/plain-react-state-lightswitch#1]
I cloned the project, cd into `plain-react-state-lightswitch` and did `yarn` and `yarn start`    

This is a screenshot of the error

![screen shot 2019-02-19 at 2 59 39 pm](https://user-images.githubusercontent.com/1719818/53043739-1fb0f280-3457-11e9-805f-b6d6b5ea3e7e.png)

**Comment by anthonybrown** [comment]
I'm running `node v11.10.0` and `npm v 6.7.0`

**Comment by anthonybrown** [comment]
`npm` works fine though, strange

**Comment by dceddia** [comment]
That's a strange one. Just tried and it worked ok for me. It looks like it was an issue a while ago in Create React App (https://github.com/facebook/create-react-app/issues/752), something to do with upgrades... probably unrelated to this though. My versions:

```
$ node -v
v10.1.0
$ npm -v
6.0.1
$ yarn -v
1.13.0
```

Maybe something to do with your version of yarn? I'll close this for now since it's working with npm.
